AVAILABLE_INTERESTS = [
    "Technology",
    "Design",
    "Language Exchange",
    "AI",
    "Music",
    "Fitness",
    "Startups",
    "Education",
    "Gaming",
    "Cooking",
    "Photography",
    "Travel",
    "Science",
    "Health",
    "Art",
    "Writing",
    "Finance",
    "Environment",
    "Sports",
    "Volunteering",
]
